# Save this as .github/workflows/deploy.yml
name: Deploy YODA to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - 'worker/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy YODA Worker
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      # Deploy from the worker directory
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'worker'
          command: publish
      
      - name: Deployment Success
        if: success()
        run: |
          echo "✅ YODA deployed successfully!"
          echo "🌐 Dashboard: https://yoda-mobile.michaelarobards.workers.dev/dashboard"
          echo "📊 Check the Actions tab for deployment history"
